version: '3.8'
services:

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - user-service
      - product-service
      - cart-service
      - order-service

  user-db:
    image: postgres:15
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"

  product-db:
    image: postgres:15
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"

  cart-db:
    image: postgres:15
    environment:
      POSTGRES_DB: cartdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"

  order-db:
    image: postgres:15
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5436:5432"

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - user-db
      - config-server

  product-service:
    build: ./product-service
    ports:
      - "8082:8082"
    depends_on:
      - product-db
      - config-server

  cart-service:
    build: ./cart-service
    ports:
      - "8083:8083"
    depends_on:
      - cart-db
      - config-server

  order-service:
    build: ./order-service
    ports:
      - "8084:8084"
    depends_on:
      - order-db
      - config-server