spring:
  application:
    name: CartService

  datasource:
    url: jdbc:postgresql://localhost:5432/cart_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    config:
      enabled: false

server:
  port: 8083

logging:
  level:
    org.springframework: INFO
    com.grocery.cartservice: DEBUG