spring:
  application:
    name: config-server

  server:
    port: 8888

  cloud:
    config:
      server:
        git:
          uri: https://github.com/PalakDave1229/grocery-config
          default-label: main
          clone-on-start: true
